# ==========================================================
# Z1 Mega Demo Script: "Factory Daydream"
# - Stress test: long, mixed To/By, lots of state changes
# - Poses are mostly repeatable using rotateJointTo
# - Motion accents (wobble, grip, shake) use rotateJointBy
#
# Created By: SaltyJxss
# Partially generated by AI
# ==========================================================

# LOAD THE ARM
load(robot, Z1)

# ----------------------------------------------------------
# SECTION 0: Boot / calibration wiggle
# ----------------------------------------------------------
rotateJointTo(link01,  60,   0)
rotateJointTo(link02,  60,  10)
rotateJointTo(link03,  60, -25)
rotateJointTo(link04,  70,   0)
rotateJointTo(link05,  70,   0)
rotateJointTo(link06, 120,   0)

# tiny "servos alive" buzz
rotateJointBy(link02,  40,  -2)
rotateJointBy(link03,  40,   2)
rotateJointBy(link02,  40,   2)
rotateJointBy(link03,  40,  -2)
rotateJointBy(link04,  50,   1)
rotateJointBy(link04,  50,  -1)


# ----------------------------------------------------------
# SECTION 1: Panorama scan (base yaw sweep) + stabilization
# ----------------------------------------------------------
rotateJointTo(link01,  80,  45)
rotateJointTo(link02,  50,   8)
rotateJointTo(link03,  50, -22)

rotateJointTo(link01,  80, -45)
rotateJointTo(link02,  50,  12)
rotateJointTo(link03,  50, -28)

rotateJointTo(link01,  80,   0)
rotateJointTo(link02,  50,  10)
rotateJointTo(link03,  50, -25)

# "camera stabilization" micro corrections
rotateJointBy(link04,  60,  2)
rotateJointBy(link05,  60, -2)
rotateJointBy(link04,  60, -2)
rotateJointBy(link05,  60,  2)


# ----------------------------------------------------------
# SECTION 2: Approach A (pre-grasp) -> nudge -> grip -> lift
# ----------------------------------------------------------
# Pre-grasp pose A
rotateJointTo(link01,  70,  25)
rotateJointTo(link02,  60, -20)
rotateJointTo(link03,  60,  30)
rotateJointTo(link04,  70,  15)
rotateJointTo(link05,  70,  10)
rotateJointTo(link06, 140,   0)

# Fine approach nudges
rotateJointBy(link02,  35,  -5)
rotateJointBy(link03,  35,   7)
rotateJointBy(link04,  45,   4)
rotateJointBy(link05,  45,   2)

# "Grip" (wrist roll + slight pitch)
rotateJointBy(link06, 180,  35)
rotateJointBy(link05,  80, -12)
rotateJointBy(link06, 180, -10)
rotateJointTo(link06, 160,  15)     # snap to repeatable roll

# Lift pose A
rotateJointTo(link03,  60,  10)
rotateJointTo(link02,  60, -10)
rotateJointTo(link04,  70,   5)
rotateJointTo(link05,  70,   5)


# ----------------------------------------------------------
# SECTION 3: Carry path (turn + wrist "anti-swing")
# ----------------------------------------------------------
rotateJointTo(link01,  80,  70)

# anti-swing oscillation (small, looks like compensation)
rotateJointBy(link04,  80,  3)
rotateJointBy(link04,  80, -3)
rotateJointBy(link05,  80, -2)
rotateJointBy(link05,  80,  2)
rotateJointBy(link04,  80,  2)
rotateJointBy(link04,  80, -2)

# Mid-carry posture adjust
rotateJointTo(link02,  55, -15)
rotateJointTo(link03,  55,  15)


# ----------------------------------------------------------
# SECTION 4: Place A (approach -> release -> retreat)
# ----------------------------------------------------------
rotateJointTo(link02,  55, -22)
rotateJointTo(link03,  55,  25)
rotateJointTo(link04,  65,  12)
rotateJointTo(link05,  65,   8)

# Place micro nudges
rotateJointBy(link02,  30,  -3)
rotateJointBy(link03,  30,   4)
rotateJointBy(link04,  40,   2)

# Release
rotateJointBy(link06, 180, -20)
rotateJointBy(link05,  90,   8)
rotateJointBy(link06, 180,  -8)
rotateJointTo(link06, 160,   0)
rotateJointTo(link05,  80,   0)

# Retreat clean
rotateJointTo(link04,  60,   0)
rotateJointTo(link03,  60,   0)
rotateJointTo(link02,  60,   5)


# ----------------------------------------------------------
# SECTION 5: Approach B (different yaw, different pose)
# ----------------------------------------------------------
rotateJointTo(link01,  85, -60)
rotateJointTo(link02,  60, -30)
rotateJointTo(link03,  60,  45)
rotateJointTo(link04,  70,  20)
rotateJointTo(link05,  70,  12)
rotateJointTo(link06, 160,   0)

# jittery "search" near object
rotateJointBy(link01,  70,   6)
rotateJointBy(link01,  70,  -6)
rotateJointBy(link02,  45,  -4)
rotateJointBy(link02,  45,   4)
rotateJointBy(link03,  45,   5)
rotateJointBy(link03,  45,  -5)

# Commit approach B
rotateJointBy(link02,  35,  -6)
rotateJointBy(link03,  35,   8)
rotateJointBy(link04,  45,   6)

# Grip B (more dramatic)
rotateJointBy(link06, 200,  50)
rotateJointBy(link05, 100, -14)
rotateJointBy(link06, 200, -20)
rotateJointTo(link06, 180,  25)

# Lift B
rotateJointTo(link03,  60,  15)
rotateJointTo(link02,  60, -12)
rotateJointTo(link04,  70,   0)
rotateJointTo(link05,  70,   4)


# ----------------------------------------------------------
# SECTION 6: "Quality check" flourish (shake + rotate wrist)
# ----------------------------------------------------------
# gentle shake (base + shoulder)
rotateJointBy(link01, 120,  10)
rotateJointBy(link01, 120, -20)
rotateJointBy(link01, 120,  10)

rotateJointBy(link02,  80,   6)
rotateJointBy(link02,  80,  -6)

# wrist roll inspection
rotateJointBy(link06, 220,  60)
rotateJointBy(link06, 220, -60)
rotateJointTo(link06, 180,  25)


# ----------------------------------------------------------
# SECTION 7: Place B (new drop area)
# ----------------------------------------------------------
rotateJointTo(link01,  90, -20)
rotateJointTo(link02,  55, -18)
rotateJointTo(link03,  55,  22)
rotateJointTo(link04,  65,  10)
rotateJointTo(link05,  65,   8)

# tiny align
rotateJointBy(link04,  45,   2)
rotateJointBy(link05,  45,  -2)

# release B
rotateJointBy(link06, 200, -25)
rotateJointBy(link05, 100,  10)
rotateJointBy(link06, 200, -10)
rotateJointTo(link06, 160,   0)
rotateJointTo(link05,  80,   0)

# retreat
rotateJointTo(link04,  60,   0)
rotateJointTo(link03,  60,  -5)
rotateJointTo(link02,  60,   5)


# ----------------------------------------------------------
# SECTION 8: "Dance mode" (stress test lots of commands)
# ----------------------------------------------------------
rotateJointTo(link01, 120,  90)
rotateJointTo(link02,  80,   0)
rotateJointTo(link03,  80, -20)
rotateJointTo(link04, 120,  30)
rotateJointTo(link05, 120, -10)
rotateJointTo(link06, 240,   0)

rotateJointBy(link01, 160, -30)
rotateJointBy(link02, 120,  15)
rotateJointBy(link03, 120, -20)
rotateJointBy(link04, 160,  10)
rotateJointBy(link05, 160,  15)
rotateJointBy(link06, 260,  90)

rotateJointBy(link01, 160,  60)
rotateJointBy(link02, 120, -15)
rotateJointBy(link03, 120,  20)
rotateJointBy(link04, 160, -10)
rotateJointBy(link05, 160, -15)
rotateJointBy(link06, 260, -180)

rotateJointBy(link01, 160, -30)
rotateJointBy(link06, 260,  90)

# snap back from dance to safe-ish posture
rotateJointTo(link01, 100,   0)
rotateJointTo(link02,  80,  10)
rotateJointTo(link03,  80, -25)
rotateJointTo(link04, 100,   0)
rotateJointTo(link05, 100,   0)
rotateJointTo(link06, 200,   0)


# ----------------------------------------------------------
# SECTION 9: End: slow "bow" then neutral
# ----------------------------------------------------------
rotateJointTo(link02,  35, -10)
rotateJointTo(link03,  35,  10)
rotateJointTo(link04,  35,  15)
rotateJointBy(link06, 120,  20)
rotateJointBy(link06, 120, -20)

rotateJointTo(link02,  40,  10)
rotateJointTo(link03,  40, -25)
rotateJointTo(link04,  60,   0)
rotateJointTo(link05,  60,   0)
rotateJointTo(link06, 160,   0)

# ==========================================================
# End of script
# ==========================================================
